GN-54 Add skip to content link after search box
nice-digital/global-nav pull request #111
Opened 2021-05-26 09:43 UTC by wa-rren-dev

https://nicedigital.atlassian.net/browse/GN-54

2021-05-26 09:45 UTC, wa-rren-dev commented
https://user-images.githubusercontent.com/6341474/119639416-7fa15b00-be0f-11eb-95d0-6e363b7fc475.mov

2021-05-26 10:37 UTC, ediblecode requested changes

2021-05-26 10:37 UTC, ediblecode commented on src/Header/Search/__snapshots__/Search.test.jsx.snap
> +    href="#undefined"
I think this test would be better to pass in a `skipLinkId` prop so that the snapshot makes more sense

2021-05-26 10:37 UTC, ediblecode commented on src/Header/Search/Search.jsx
> +					onClick={this.handleClick}
Where is `handleClick` defined? It doesn't look like it is to me!

2021-05-26 18:37 UTC, ediblecode commented on src/Header/SkipLink/SkipLink.jsx
> +	to: PropTypes.string,
Just small thing here - I think the `to` prop is required, and `label` isn't needed

2021-05-27 12:14 UTC, ediblecode commented on src/Header/Search/Search.jsx
> +					onClick={this.handleClick}
Ignore that - it was already in that class

2021-05-27 12:22 UTC, ediblecode approved these changes

2021-06-10 10:46 UTC, merged